---
abstract: 'L<TPath::Forester> that understands file systems'
author:
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Exporter: 0
  File::Path: 0
  File::Temp: 0
  FindBin: 0
  Test::More: 0.88
  Test::Script: 1.05
  autodie: 0
  base: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TPath-Forester-File
no_index: {}
requires:
  Cwd: 0
  Encode: 0
  Encode::Detect::Detector: 0
  Fcntl: 0
  File::Spec: 0
  File::stat: 0
  Getopt::Long::Descriptive: 0
  Module::Load::Conditional: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  MooseX::MethodAttributes::Role: 0
  Pod::Usage: 0
  TPath: 0.016
  TPath::Forester: 0
  TPath::Index: 0
  filetest: 0
  namespace::autoclean: 0
  overload: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
version: 0.001
